### PR TITLE
LMPC with optimization of the initial state

### PR DESCRIPTION
**Pull request by ndehio**
In this pull request, I added a class `InitialStateLMPC` that derives from `LMPC`. It includes the initial state as additional optimization variables, which may be bounded via the `resetInitialStateBounds()` function.
A separate test file demonstrates its usage. 
The underlying idea is part of my [ICRA-2021 paper](https://hal.archives-ouvertes.fr/hal-02973947/document).

### CODE REVIEW

**Comment by vsamy** [comment]
Hi,

Thank you for the PR. :)
I will start checking the code itself but it seems that the tests are failing with a Core dumped.
I can not accept the PR until this is fixed.

**Comment by vsamy** [comment]
I see you are using `<Eigen/LU>`. Be careful, some algorithms are non-MPL2 licensed. 
To ensure you are not using non-MPL2 features, add `EIGEN_MPL2_ONLY` from CMake definitions.

**Comment by ndehio** [comment]
@vsamy I am computing the inverse of a eigen-matrix [here](https://github.com/ndehio/copra/blob/master/src/InitialStateLMPC.cpp#L223) and that's why I added `#include <Eigen/LU>`.

I just added `set(EIGEN_MPL2_ONLY 1)` to the cmake, but it seems there are still problems...

**Comment by vsamy** [comment]
You have modified the constraint/cost in a hard way. Someone who would want to use the vanilla LMPC would have to provide the X,Y,z,etc matrices that it does know about.

Since you have inherited the LMPC for yours, you could do the same for all constraints and costs to avoid the problem.

**Pull request merged**
